from .nodes.intp import INTP_CLASS_MAPPING, INTP_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **INTP_CLASS_MAPPING,
}

WEB_DIRECTORY = "./web"

NODE_DISPLAY_NAME_MAPPINGS = {
    **INTP_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']